---
title: "data cleaning"
author: "Jiacheng"
date: "2022-10-10"
output: html_document
---
```{r}
library(ggplot2)
library(gridExtra)
library(dplyr)
library(colorspace)
library(corrplot)
library(ggpubr)
library(ggalt) 
library(car)
library(nlme)
library(reshape2)
library(RColorBrewer)
```

```{r}
fat <- read.csv(file = "Data/df11.csv",header=T)
fat=fat[,-1]
head(fat)
```
```{r}
nrow(fat)
colnames(fat_3)
dataprcompR <- prcomp(fat_3[,-c(1,13)], center = TRUE,
                           scale. = TRUE, # 基于样本相关系数矩阵 R
                           retx = TRUE)
screeplot(dataprcompR, type = "line")
summary(dataprcompR)
round(dataprcompR$rotation,3)
```



```{r}
colnames(fat) <- c("Y","X2","X3","X4","X5","X6","X7","X8","X9","X10","X11","X12","X13","X14","X15")
head(fat)
```

```{r}
# 全模型的线性回归(还没有变量选择的不显著的变量也在模型里面)
mlr <- lm(Y ~ X2 + X3 +X4+ X5 + X6 + X7 + X8 + X9 + X10 + X11 + X12 + X13 + X14 + X15, fat)
step(mlr,direction="both")
summary(mlr)
summary(aov(mlr))
plot(rstandard(mlr)~fitted(mlr),xlab='y_fit',ylab = 'y.rst',main='fit')
car::ncvTest(mlr)
summary(aov(mlr))
# 置信区间
confint(mlr)
```
```{r}
mlr5 <- lm(Y ~ X2 +  X5 + X6 + X7 + X8 + X9 + X10 + X11 + X12 + X13 + X14 + X15, fat)
summary(mlr5)
summary(aov(mlr5))
plot(rstandard(mlr5)~fitted(mlr5),xlab='y_fit',ylab = 'y.rst',main='fit')
car::ncvTest(mlr5)
summary(aov(mlr5))
# 置信区间
confint(mlr5)

fat_3<-fat[,c(1,2,5,6,7,8,9,10,11,12,13,14,15)]
fitmodel5<-lm(Y~.,data = fat_3)
fitmodel5
vif_fat5<-vif(fitmodel5)
vif_fat5
```

```{r}
# 全模型的线性回归(还没有变量选择的不显著的变量也在模型里面)
mlr2 <- lm(Y ~ X2 +X5 + X6 + X7 + X8 + X9 + X15, fat)
summary(mlr2)
summary(aov(mlr2))
plot(rstandard(mlr2)~fitted(mlr2),xlab='y_fit',ylab = 'y.rst',main='fit')
car::ncvTest(mlr2)
summary(aov(mlr2))
# 置信区间
confint(mlr2)
fat_first<-fat[,c(1,2,5,6,8,10,15)]
#fat_first

#五个变量的多重共线性
kappa(fat_first,exact=TRUE)
fitmodel1<-lm(Y~.,data = fat_first)
fitmodel1
vif_fat1<-vif(fitmodel1)
vif_fat1
cor_data1<-cor(fat_first)
kappa(cor_data1,exact=TRUE)
eigen(cor_data1)

fat_sec<-fat[,c(1,2,5,6,8,15)]
#fat_first
kappa(fat_sec,exact=TRUE)
fitmodel2<-lm(Y~.,data = fat_sec)
fitmodel2
vif_fat2<-vif(fitmodel2)
vif_fat2
cor_data2<-cor(fat_sec)
kappa(cor_data2,exact=TRUE)
eigen(cor_data2)
```
```{r}
mlr3 <- lm(Y ~ X5 +X7+ X8 +X9 + X15, fat)
plot(mlr3)
hist(fat$X7)
summary(mlr3)
summary(aov(mlr3))
plot(rstandard(mlr3)~fitted(mlr3),xlab='y_fit',ylab = 'y.rst',main='fit')
car::ncvTest(mlr3)
summary(aov(mlr3))
anova(mlr2,mlr3)

# 假设检验（对最不显著变量X6）
linearHypothesis(mlr3,c(0,0,0,1,0,0),rhs = c(0))
a1=aov(Y ~ X2 +X5 + X6 + X8  + X15, fat_sec)
a1
```
```{r}
#逐步回归（对全模型的向前和向后回归）
mlr.step = lm(Y ~ X2 +  X5 + X6 + X8  + X15, fat_sec)
step(mlr.step, direction = "backward")
step(mlr.step, direction = "forward")
```


```{r}
#逐步回归（混合性）
mlr.step3=step(mlr3)
summary(mlr.step3)
drop1(mlr.step3)#逐步回归的优化
```

```{r}
mlr4 <- lm(Y ~ X2 +X5 + X8 + X15, fat)
summary(mlr4)
summary(aov(mlr4))
plot(rstandard(mlr4)~fitted(mlr4),xlab='y_fit',ylab = 'y.rst',main='fit')
car::ncvTest(mlr4)
summary(aov(mlr4))
```


```{r}
# AIC
AIC(lm(Y ~ X2 + X5  + X8 , fat_first))
AIC(lm(Y ~ X2 + X5  +X15, fat_first))
AIC(lm(Y ~ X5  + X8 +X15, fat_first))
AIC(lm(Y ~ X2  + X8 +X15, fat_first))
AIC(lm(Y ~ X2 + X5  + X8 +X15, fat_first))
AIC(lm(Y ~ X2 + X5  + X6 + X8 + X15, fat_first))

# BIC
BIC(lm(Y ~ X2 + X5  + X8 , fat_first))
BIC(lm(Y ~ X2 + X5  +X15, fat_first))
BIC(lm(Y ~ X5  + X8 +X15, fat_first))
BIC(lm(Y ~ X2  + X8 +X15, fat_first))
BIC(lm(Y ~ X2 + X5  + X8 +X15, fat_first))
BIC(lm(Y ~ X2 + X5  + X6 + X8 + X15, fat_first))
```
```{r}
model1<-lm(Y ~ X2 + X5  + X8 , fat_first)
model2<-lm(Y ~ X2 + X5  +X15, fat_first)
model3<-lm(Y ~ X5  + X8 +X15, fat_first)
model4<-lm(Y ~ X2  + X8 +X15, fat_first)
model5<-lm(Y ~ X2 + X5  + X8 +X15, fat_first)
model6<-lm(Y ~ X2 + X5  + X6 + X8 + X15, fat_first)
model7<-lm(Y ~ X2 + X5  + X6 + X8 +X10 + X15, fat_first)
anova(model5,model6)
anova(model6,model7)
summary(model1)$adj.r.squared
summary(model2)$adj.r.squared
summary(model3)$adj.r.squared
summary(model4)$adj.r.squared
summary(model5)$adj.r.squared
summary(model6)$adj.r.squared
summary(model7)$adj.r.squared

model_sum1 <-summary(model1)
model_sum2 <-summary(model2)
model_sum3 <-summary(model3)
model_sum4 <-summary(model4)
model_sum5 <-summary(model5)
model_sum6 <-summary(model6)
model_sum7 <-summary(model7)
mean(model_sum1$residuals^2)
mean(model_sum2$residuals^2)
mean(model_sum3$residuals^2)
mean(model_sum4$residuals^2)
mean(model_sum5$residuals^2)
mean(model_sum6$residuals^2)
mean(model_sum7$residuals^2)

data1 <- data.frame(pred = predict(model1), actual = fat_first$Y)
head(data1)
mean((data1$actual - data1$pred)^2)
data2 <- data.frame(pred = predict(model2), actual = fat_first$Y)
head(data2)
mean((data2$actual - data2$pred)^2)
data3 <- data.frame(pred = predict(model3), actual = fat_first$Y)
head(data3)
mean((data3$actual - data3$pred)^2)
data4 <- data.frame(pred = predict(model4), actual = fat_first$Y)
head(data4)
mean((data4$actual - data4$pred)^2)
data5 <- data.frame(pred = predict(model5), actual = fat_first$Y)
head(data5)
mean((data5$actual - data5$pred)^2)
data6 <- data.frame(pred = predict(model6), actual = fat_first$Y)
head(data6)
mean((data6$actual - data6$pred)^2)
```
