---
title: "data cleaning"
author: "Jiacheng"
date: "2022-10-10"
output: html_document
---
```{r}
library(ggplot2)
library(gridExtra)
library(dplyr)
library(colorspace)
library(corrplot)
library(ggpubr)
library(ggalt) 
library(car)
library(nlme)
library(reshape2)
library(RColorBrewer)
```

```{r}
fat <- read.csv(file = "/Users/yujiacheng/Desktop/628/BodyFat.csv",header=T)
fat=fat[,-1]
head(fat)
```
```{r}
missing_row <- fat[!complete.cases(fat),]  #检查有无缺损项
head(missing_row)
fat$AGE_class<-ifelse(fat$AGE<=40,"22-40",ifelse(fat$AGE<=60,"41-60","61-81"))
require("RColorBrewer")
counttable<-table(fat$AGE_class)
barplot(counttable,col=brewer.pal(3, "RdGy")[fat$AGE_class],
        main = "AGE",xlab="Age",ylab="COUNT")
legend("topright", col =brewer.pal(3, "RdGy")[fat$AGE_class],
       pch=c(20,20,20), bty = "n",
       legend = c("22-40", "41-60","61-81"))

```
```{r}
kappa(fat,,exact=TRUE)
fitmodel<-lm(BODYFAT~.,data = fat)
fitmodel
vif_fat<-vif(fitmodel)
vif_fat
cor_data<-cor(fat)
kappa(cor_data,,exact=TRUE)
eigen(cor_data)
```

```{r}
# 相关系数矩阵（全部当成是连续性的变量X）
corr1 <-  round(cor(fat),3)
knitr::kable(corr1)
corrplot(corr1,method = "number")
```

```{r}
head(fat)
d1=density(fat$BODYFAT)
plot(d1,main="Kernel Density of BODYFAT")
polygon(d1,col="dark grey",border="light green")
fat$log_BODYFAT <- log(fat$BODYFAT*10)#对BODYFAT进行对数变换
d2=density(fat$log_BODYFAT)
plot(d2,main="Kernel Density of log(BODYFAT)")
polygon(d2,col="dark grey",border="light green")#对数变换后的BODYFAT的直方图
```


```{r}
colnames(fat) <- c("Y","X1","X2","X3","X4","X5","X6","X7","X8","X9","X10","X11","X12","X13","X14","X15")
```

```{r}
# 全模型的线性回归(还没有变量选择的不显著的变量也在模型里面)
mlr <- lm(Y ~ X2 + X3 +X4+ X5 + X6 + X7 + X8 + X9 + X10 + X11 + X12 + X13 + X14 + X15, fat)
summary(mlr)
summary(aov(mlr))
plot(rstandard(mlr)~fitted(mlr),xlab='y_fit',ylab = 'y.rst',main='fit')
car::ncvTest(mlr)
summary(aov(mlr))
# 置信区间
confint(mlr)
```
```{r}
# 全模型的线性回归(还没有变量选择的不显著的变量也在模型里面)
mlr2 <- lm(Y ~ X2 +  X6 + X8 + X14 + X15, fat)
summary(mlr2)
summary(aov(mlr2))
plot(rstandard(mlr2)~fitted(mlr2),xlab='y_fit',ylab = 'y.rst',main='fit')
car::ncvTest(mlr2)
summary(aov(mlr2))
# 置信区间
confint(mlr2)
fat_first<-fat[,c(1,3,7,9,15,16)]
fat_first

#五个变量的多重共线性
kappa(fat_first,,exact=TRUE)
fitmodel1<-lm(Y~.,data = fat_first)
fitmodel1
vif_fat1<-vif(fitmodel1)
vif_fat1
cor_data1<-cor(fat_first)
kappa(cor_data1,,exact=TRUE)
eigen(cor_data1)
```
```{r}
# 假设检验（对最不显著变量X6）
linearHypothesis(mlr2,c(0,0,1,0,0,0),rhs = c(0))
a1=aov(Y ~ X2 +  X6 + X8 + X14 + X15, fat_first)
a1
# 假设检验（对最不显著变量X14）
linearHypothesis(mlr2,c(0,0,0,0,1,0),rhs = c(0))
a2=aov(Y ~ X2 +  X6 + X8 + X14 + X15, fat_first)
a2
```
```{r}
#逐步回归（对全模型的向前和向后回归）
mlr.step = lm(Y ~ X2 +  X6 + X8 + X14 + X15, fat_first)
step(mlr.step, direction = "backward")
step(mlr.step, direction = "forward")
```


```{r}
#逐步回归（混合性）
mlr.step2=step(mlr2)
summary(mlr.step2)
drop1(mlr.step2)#逐步回归的优化
```


```{r}
# AIC
AIC(lm(Y ~ X2 + X8 + X15, fat_first))
AIC(lm(Y ~ X2 + X8 + X15 + X6, fat_first))
AIC(lm(Y ~ X2 + X8 + X15 + X14, fat_first))
AIC(lm(Y ~ X2 + X8 + X15 + X6 + X14, fat_first))

# BIC
BIC(lm(Y ~ X2 + X8 + X15, fat_first))
BIC(lm(Y ~ X2 + X8 + X15 + X6, fat_first))
BIC(lm(Y ~ X2 + X8 + X15 + X14, fat_first))
BIC(lm(Y ~ X2 + X8 + X15 + X6 + X14, fat_first))
```
```{r}
model1<-lm(Y ~ X2 + X8 + X15, fat_first)
model2<-lm(Y ~ X2 + X8 + X15 + X6, fat_first)
model3<-lm(Y ~ X2 + X8 + X15 + X14, fat_first)
model4<-lm(Y ~ X2 + X8 + X15 + X6 + X14, fat_first)
summary(model1)$adj.r.squared
summary(model2)$adj.r.squared
summary(model3)$adj.r.squared
summary(model4)$adj.r.squared

model_sum1 <-summary(model1)
model_sum2 <-summary(model2)
model_sum3 <-summary(model3)
model_sum4 <-summary(model4)
mean(model_sum1$residuals^2)
mean(model_sum2$residuals^2)
mean(model_sum3$residuals^2)
mean(model_sum4$residuals^2)

data1 <- data.frame(pred = predict(model1), actual = fat_first$Y)
head(data1)
mean((data1$actual - data1$pred)^2)
data2 <- data.frame(pred = predict(model2), actual = fat_first$Y)
head(data2)
mean((data2$actual - data2$pred)^2)
data3 <- data.frame(pred = predict(model3), actual = fat_first$Y)
head(data3)
mean((data3$actual - data3$pred)^2)
data4 <- data.frame(pred = predict(model4), actual = fat_first$Y)
head(data4)
mean((data4$actual - data4$pred)^2)
```
